# Generated by Django 4.0.2 on 2022-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Архив', 'Архив'), ('Ожиданы', 'Ожиданы'), ('Встреча', 'Встреча'), ('Договор', 'Договор')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание'), ('Аванс', 'Аванс')], default='Ожидание', max_length=120),
        ),
    ]
