# Generated by Django 4.0.2 on 2022-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_clients_form_alter_clients_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Архив', 'Архив'), ('Договор', 'Договор'), ('Ожиданы', 'Ожиданы'), ('Встреча', 'Встреча')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Аванс', 'Аванс'), ('Ожидание', 'Ожидание'), ('Оплачено', 'Оплачено')], default='Ожидание', max_length=120),
        ),
    ]
