# Generated by Django 4.0.2 on 2022-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Договор', 'Договор'), ('Встреча', 'Встреча'), ('Архив', 'Архив'), ('Ожиданы', 'Ожиданы')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Аванс', 'Аванс'), ('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание')], default='Ожидание', max_length=120),
        ),
    ]
