# Generated by Django 4.0.2 on 2022-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_clients_status_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Архив', 'Архив'), ('Ожиданы', 'Ожиданы'), ('Договор', 'Договор')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Аванс', 'Аванс'), ('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание')], default='Ожидание', max_length=120),
        ),
    ]
