# Generated by Django 4.0.2 on 2022-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_clients_status_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Ожиданы', 'Ожиданы'), ('Договор', 'Договор'), ('Архив', 'Архив')], default='Ожиданы', max_length=120, null=True),
        ),
    ]
