# Generated by Django 4.0.2 on 2022-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_clients_form_alter_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Ожиданы', 'Ожиданы'), ('Архив', 'Архив'), ('Договор', 'Договор'), ('Встреча', 'Встреча')], default='Ожиданы', max_length=120, null=True),
        ),
    ]
